use customer_behaviour_analysis;
show tables;

select * from customer_behaviour limit 4;

# 1) what is the total revenue generated by male vs female customers?

select gender,sum(purchase_amount) as revenue from customer_behaviour group by gender;

# 2) Which customers used a discount but still spent more than the average purchase amount? 
 
 select customer_id,purchase_amount from customer_behaviour where discount_applied='yes' 
 and purchase_amount>(select avg(purchase_amount) from customer_behaviour);
 
 # 3) Which are the top 5 products with the highest average review rating?
 
 select item_purchased, round(avg(review_rating),2) as Average_Product_ating
from customer_behaviour
group by item_purchased
order by avg(review_rating) desc
limit 5;

# 4) Compare the average Purchase Amounts between Standard and Express Shipping.

# insight customers are purchasing the items through express mode more than standard

select shipping_type,round(avg(purchase_amount),1) as spent_amount from customer_behaviour
where shipping_type in ('Express','Standard') group by shipping_type; 

# 5) Do subscribed customers spend more? Compare average spend and total revenue 
     -- between subscribers and non-subscribers.
SELECT subscription_status,
       COUNT(customer_id) AS total_customers,
       ROUND(AVG(purchase_amount),2) AS avg_spend,
       ROUND(SUM(purchase_amount),2) AS total_revenue
FROM customer_behaviour
GROUP BY subscription_status
ORDER BY total_revenue,avg_spend DESC;

# 6) Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased,
       ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
FROM customer_behaviour
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

-# 7). Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM customer_behaviour
WHERE previous_purchases > 5
GROUP BY subscription_status;

# 8). What is the revenue contribution of each age group? 
SELECT 
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM customer_behaviour
GROUP BY age_group
ORDER BY total_revenue desc;